# Data Preprocessing
The data preprocessing is done in get_original_post.py.

# Analysis of Efficiency

In [1]:
import pandas as pd
import pickle

In [2]:
with open(("./data/df_pre2019_original.pickle"), 'rb') as handle:
    data = pickle.load(handle)

In [3]:
data['confirmed_time'] = data['created_utc'] - data['created_utc_original']
# Delete the rows with confirmed_time < 0. Outliers. Two rows.
data = data[data['confirmed_time'] >= pd.Timedelta(0)]

In [5]:
data.head()

,user,index,author,body,created_utc,permalink,reply_author,reply_body,type,pred,subreddit,url,created_utc_original,confirmed_time
6,rdmentalist,rdmentalist_2,MrAce2C,Successful trade with u/rdmentalist. Gave Gear...,2016-10-23 21:59:35,/r/gameswap/comments/543ojp/completed_trade_th...,rdmentalist,Confirmed.,gameswap,NaN,gameswap,r/gameswap/comments/5906ut,2016-10-23 19:16:49,0 days 02:42:46
9,rdmentalist,rdmentalist_5,TradlyGent,swapped a 20% PSN code for Gears of War 1 and ...,2018-07-03 17:19:14,/r/gameswap/comments/7q4pkv/completed_swap_thr...,rdmentalist,Confirmed.,gameswap,NaN,gameswap,r/gameswap/comments/8pg7m1,2018-06-08 02:20:56,25 days 14:58:18
10,rdmentalist,rdmentalist_6,keokidream,Successful trade with /u/rdmentalist\n\nCall o...,2016-06-17 14:54:23,/r/gameswap/comments/4c351t/completed_trade_th...,rdmentalist,Confirmed! thanks,gameswap,NaN,gameswap,r/gameswap/comments/4ogyyf,2016-06-17 01:58:26,0 days 12:55:57
11,rdmentalist,rdmentalist_7,testicles_two,"Traded Gears of War 1,2,3 and Judgement for $1...",2016-06-23 23:55:01,/r/gameswap/comments/4c351t/completed_trade_th...,rdmentalist,Confirmed ! thanks,gameswap,NaN,gameswap,r/gameswap/comments/4ovjzx,2016-06-19 22:29:56,4 days 01:25:05
12,rdmentalist,rdmentalist_8,walterpwn,Successful trade with [/u/rdmentalist](https:/...,2016-05-12 19:43:00,/r/gameswap/comments/4c351t/completed_trade_th...,rdmentalist,Confirmed :),gameswap,NaN,gameswap,r/gameswap/comments/4iuc98,2016-05-11 10:49:48,1 days 08:53:12

## Total confirmations.

In [6]:
# Get the confirmed_time summary, grouping by type.
confirmed_time_summary = data.groupby('type')['confirmed_time'].describe()
confirmed_time_summary

,count,mean,std,min,25%,50%,75%,max
type,,,,,,,,
gamesale,19512,11 days 10:58:53.021217712,33 days 15:06:44.659587127,0 days 00:06:35,1 days 13:24:52,5 days 17:46:42,10 days 03:20:08,1128 days 19:27:40
gameswap,9190,19 days 19:46:55.840261153,58 days 04:01:00.876948658,0 days 00:17:47,7 days 02:58:05,11 days 05:29:19,17 days 11:40:53.750000,1325 days 09:32:34

## Confirmed in one week.

In [7]:
confirmed_one_data = data.loc[data['confirmed_time']<=pd.Timedelta(1, unit='w')]
confirmed_one_data.groupby('type')['confirmed_time'].describe()

,count,mean,std,min,25%,50%,75%,max
type,,,,,,,,
gamesale,11582,2 days 20:15:42.291055085,2 days 08:05:02.467828605,0 days 00:06:35,0 days 10:28:47.750000,2 days 19:29:08.500000,4 days 23:58:28,6 days 23:58:42
gameswap,2176,4 days 01:10:50.295036764,2 days 06:42:25.744408899,0 days 00:17:47,1 days 23:38:26.750000,4 days 17:08:48,6 days 00:20:49,6 days 23:46:26